"""add microposts table

Revision ID: a35df0cf3400
Revises: dcd2c7341d8f
Create Date: 2021-08-30 05:07:42.737557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35df0cf3400'
down_revision = 'dcd2c7341d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microposts',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microposts_title'), 'microposts', ['title'], unique=False)

    with op.batch_alter_table("books") as batch_op:
        batch_op.drop_column('books', 'alt_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('alt_text', sa.VARCHAR(length=120), nullable=True))
    op.drop_index(op.f('ix_microposts_title'), table_name='microposts')
    op.drop_table('microposts')
    # ### end Alembic commands ###
