"""create user table

Revision ID: bb551bf45ee8
Revises: 985c4313fa75
Create Date: 2021-08-14 15:51:10.266462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb551bf45ee8'
down_revision = '985c4313fa75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('books', sa.Column('category', sa.String(length=10), nullable=True))
    op.add_column('books', sa.Column('book_link', sa.String(length=120), nullable=True))
    op.add_column('books', sa.Column('image_link', sa.String(length=120), nullable=True))
    op.add_column('books', sa.Column('alt_text', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'alt_text')
    op.drop_column('books', 'image_link')
    op.drop_column('books', 'book_link')
    op.drop_column('books', 'category')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
