"""remove alt text from book and add admin table

Revision ID: dcd2c7341d8f
Revises: cd22722e8199
Create Date: 2021-08-29 10:56:18.924737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd2c7341d8f'
down_revision = 'cd22722e8199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("books") as batch_op:
        op.drop_column('books', 'alt_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('alt_text', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
